### Introduction:

We are going to use Apple's stock price.


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

# visualization
import matplotlib.pyplot as plt

%matplotlib inline

### Step 2. Read appl_1980_2014.csv file and assign it to a variable apple

In [6]:
apple = pd.read_csv("appl_1980_2014.csv")

### Step 3.  Check out the type of the columns

In [7]:
apple.dtypes

Date          object
Open         float64
High         float64
Low          float64
Close        float64
Volume         int64
Adj Close    float64
dtype: object

### Step 4. Transform the Date column as a datetime type

In [17]:
apple['Date'] = pd.to_datetime(apple['Date'])
apple.shape

(8465, 7)

### Step 5.  Set the date as the index

In [20]:
apple.set_index('Date')

              Open    High     Low   Close     Volume  Adj Close
Date
2014-08-07   96.27   96.80   93.92   95.35   65130000      95.35
2014-07-07   94.14   95.99   94.10   95.97   56305400      95.97
2014-03-07   93.67   94.10   93.20   94.03   22891800      94.03
2014-02-07   93.87   94.06   93.09   93.48   28420900      93.48
2014-01-07   93.52   94.07   93.13   93.52   38170200      93.52
2014-06-30   92.10   93.73   92.09   92.93   49482300      92.93
2014-06-27   90.82   92.00   90.77   91.98   64006800      91.98
2014-06-26   90.37   91.05   89.80   90.90   32595800      90.90
2014-06-25   90.21   90.70   89.65   90.36   36852200      90.36
2014-06-24   90.75   91.74   90.19   90.28   38988300      90.28
2014-06-23   91.32   91.62   90.60   90.83   43618200      90.83
2014-06-20   91.85   92.55   90.90   90.91  100813200      90.91
2014-06-19   92.29   92.30   91.34   91.86   35486400      91.86
2014-06-18   92.27   92.29   91.35   92.18   33493800      92.18
2014-06-17   92.31   92.70   91.80   92.08   29689800      92.08
2014-06-16   91.51   92.75   91.45   92.20   35561000      92.20
2014-06-13   92.20   92.44   90.88   91.28   54525000      91.28
2014-12-06   94.04   94.12   91.90   92.29   54749000      92.29
2014-11-06   94.13   94.76   93.47   93.86   45681000      93.86
2014-10-06   94.73   95.05   93.57   94.25   62777000      94.25
2014-09-06   92.70   93.88   91.75   93.70   75415000      93.70
2014-06-06  649.90  651.26  644.47  645.57   87484600      92.22
2014-05-06  646.20  649.37  642.61  647.35   75951400      92.48
2014-04-06  637.44  647.89  636.11  644.82   83870500      92.12
2014-03-06  628.46  638.74  628.25  637.54   73177300      91.08
2014-02-06  633.96  634.83  622.50  628.65   92337700      89.81
2014-05-30  637.98  644.17  628.90  633.00  141005200      90.43
2014-05-29  627.85  636.87  627.77  635.38   94118500      90.77
2014-05-28  626.02  629.83  623.78  624.01   78870400      89.14
2014-05-27  615.88  625.86  615.63  625.63   87216500      89.38
...            ...     ...     ...     ...        ...        ...
1981-01-26   32.37   32.37   32.25   32.25    6160000       0.50
1981-01-23   32.87   33.00   32.75   32.75    2805600       0.51
1981-01-22   32.87   33.13   32.87   32.87    8887200       0.51
1981-01-21   32.50   32.75   32.50   32.50    3976000       0.51
1981-01-20   32.00   32.00   31.88   31.88    7520800       0.50
1981-01-19   32.87   33.00   32.87   32.87   10393600       0.51
1981-01-16   31.12   31.12   31.00   31.00    3348800       0.48
1981-01-15   31.25   31.50   31.25   31.25    3516800       0.49
1981-01-14   30.63   30.75   30.63   30.63    3572800       0.48
1981-01-13   30.63   30.63   30.50   30.50    5762400       0.48
1981-12-01   31.88   31.88   31.62   31.62    5924800       0.49
1981-09-01   31.88   32.00   31.88   31.88    5376000       0.50
1981-08-01   30.37   30.37   30.25   30.25    9956800       0.47
1981-07-01   31.00   31.00   30.88   30.88   13921600       0.48
1981-06-01   32.37   32.37   32.25   32.25   11289600       0.50
1981-05-01   33.87   33.87   33.75   33.75    8932000       0.53
1981-02-01   34.50   34.75   34.50   34.50    5415200       0.54
1980-12-31   34.25   34.25   34.13   34.13    8937600       0.53
1980-12-30   35.25   35.25   35.12   35.12   17220000       0.55
1980-12-29   36.00   36.13   36.00   36.00   23290400       0.56
1980-12-26   35.50   35.62   35.50   35.50   13893600       0.55
1980-12-24   32.50   32.63   32.50   32.50   12000800       0.51
1980-12-23   30.88   31.00   30.88   30.88   11737600       0.48
1980-12-22   29.63   29.75   29.63   29.63    9340800       0.46
1980-12-19   28.25   28.38   28.25   28.25   12157600       0.44
1980-12-18   26.63   26.75   26.63   26.63   18362400       0.41
1980-12-17   25.87   26.00   25.87   25.87   21610400       0.40
1980-12-16   25.37   25.37   25.25   25.25   26432000       0.39
1980-12-15   27.38   27.38   27.25   27.25   43971200       0.42
1980-12-12   28.75   28.87   28.75   28.75  117258400       0.45

[8465 rows x 6 columns]

### Step 6.  Is there any duplicate dates?

In [21]:
apple[apple.duplicated(['Date'], keep=False)]

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Volume, Adj Close]
Index: []

### Step 7.  Ops...it seems the index is from the most recent date. Make the first entry the oldest date.

In [23]:
apple.sort_values(by='Date')

           Date    Open    High     Low   Close     Volume  Adj Close
8464 1980-12-12   28.75   28.87   28.75   28.75  117258400       0.45
8463 1980-12-15   27.38   27.38   27.25   27.25   43971200       0.42
8462 1980-12-16   25.37   25.37   25.25   25.25   26432000       0.39
8461 1980-12-17   25.87   26.00   25.87   25.87   21610400       0.40
8460 1980-12-18   26.63   26.75   26.63   26.63   18362400       0.41
8459 1980-12-19   28.25   28.38   28.25   28.25   12157600       0.44
8458 1980-12-22   29.63   29.75   29.63   29.63    9340800       0.46
8457 1980-12-23   30.88   31.00   30.88   30.88   11737600       0.48
8456 1980-12-24   32.50   32.63   32.50   32.50   12000800       0.51
8455 1980-12-26   35.50   35.62   35.50   35.50   13893600       0.55
8454 1980-12-29   36.00   36.13   36.00   36.00   23290400       0.56
8453 1980-12-30   35.25   35.25   35.12   35.12   17220000       0.55
8452 1980-12-31   34.25   34.25   34.13   34.13    8937600       0.53
8389 1981-01-04   24.38   24.38   24.25   24.25    8517600       0.38
8368 1981-01-05   28.38   28.62   28.38   28.38    4138400       0.44
8348 1981-01-06   33.13   33.25   33.13   33.13   12812800       0.52
8326 1981-01-07   25.87   25.87   25.75   25.75   42616000       0.40
8284 1981-01-09   21.38   21.50   21.38   21.38    9256800       0.33
8263 1981-01-10   15.25   15.37   15.25   15.25   15282400       0.24
8221 1981-01-12   18.63   18.75   18.63   18.63    5846400       0.29
8444 1981-01-13   30.63   30.63   30.50   30.50    5762400       0.48
8443 1981-01-14   30.63   30.75   30.63   30.63    3572800       0.48
8442 1981-01-15   31.25   31.50   31.25   31.25    3516800       0.49
8441 1981-01-16   31.12   31.12   31.00   31.00    3348800       0.48
8440 1981-01-19   32.87   33.00   32.87   32.87   10393600       0.51
8439 1981-01-20   32.00   32.00   31.88   31.88    7520800       0.50
8438 1981-01-21   32.50   32.75   32.50   32.50    3976000       0.51
8437 1981-01-22   32.87   33.13   32.87   32.87    8887200       0.51
8436 1981-01-23   32.87   33.00   32.75   32.75    2805600       0.51
8435 1981-01-26   32.37   32.37   32.25   32.25    6160000       0.50
...         ...     ...     ...     ...     ...        ...        ...
7    2014-06-26   90.37   91.05   89.80   90.90   32595800      90.90
6    2014-06-27   90.82   92.00   90.77   91.98   64006800      91.98
5    2014-06-30   92.10   93.73   92.09   92.93   49482300      92.93
125  2014-07-01  544.32  545.96  537.92  540.04   79302300      76.26
103  2014-07-02  521.38  522.93  517.38  519.68   92570100      73.83
84   2014-07-03  531.09  531.98  526.05  530.44   55182400      75.36
63   2014-07-04  528.02  530.90  521.89  523.47   72462600      74.37
42   2014-07-05  595.25  597.29  587.73  592.33   70716100      84.15
1    2014-07-07   94.14   95.99   94.10   95.97   56305400      95.97
124  2014-08-01  538.81  545.56  538.69  543.46   64632400      76.75
62   2014-08-04  525.19  526.12  518.70  523.44   60972100      74.36
41   2014-08-05  588.25  594.41  586.40  587.99   57574300      84.00
0    2014-08-07   96.27   96.80   93.92   95.35   65130000      95.35
123  2014-09-01  546.80  546.86  535.35  536.52   69787200      75.77
61   2014-09-04  522.64  530.49  522.02  530.32   51542400      75.34
40   2014-09-05  584.54  586.25  580.33  585.54   72899400      83.65
20   2014-09-06   92.70   93.88   91.75   93.70   75415000      93.70
122  2014-10-01  539.83  540.80  531.11  532.94   76244000      75.26
102  2014-10-02  518.66  531.99  518.00  528.99   86389800      75.15
83   2014-10-03  528.36  533.33  528.34  530.92   44646000      75.42
60   2014-10-04  530.68  532.24  523.17  523.48   59913000      74.37
19   2014-10-06   94.73   95.05   93.57   94.25   62777000      94.25
101  2014-11-02  530.61  537.75  529.50  535.96   70564200      76.14
82   2014-11-03  535.45  538.74  532.59  536.09   69806100      76.16
59   2014-11-04  519.00  522.83  517.14  519.61   67929400      73.82
18   2014-11-06   94.13   94.76   93.47   93.86   45681000      93.86
100  2014-12-02  536.95  539.56  533.24  535.92   77025200      76.13
81   2014-12-03  534.51  537.35  532.00  536.61   49831600      76.23
39   2014-12-05  587.49  593.66  587.40  592.83   53302200      84.69
17   2014-12-06   94.04   94.12   91.90   92.29   54749000      92.29

[8465 rows x 7 columns]

In [28]:
apple = apple.set_index('Date')

### Step 8. Get the last business day of each month

In [31]:
apple[apple.index.day == apple.index.days_in_month]

              Open    High     Low   Close     Volume  Adj Close
Date
2014-06-30   92.10   93.73   92.09   92.93   49482300      92.93
2014-04-30  592.64  599.43  589.80  590.09  114160200      83.83
2014-03-31  539.23  540.81  535.93  536.74   42167300      76.25
2014-02-28  529.08  532.75  522.12  526.24   92992200      74.76
2014-01-31  495.18  501.53  493.55  500.60  116199300      70.69
2013-12-31  554.17  561.28  554.00  561.02   55771100      79.23
2013-10-31  525.00  527.49  521.27  522.70   68924100      73.39
2013-09-30  477.25  481.66  474.41  476.75   65039100      66.94
2013-07-31  454.99  457.34  449.43  452.53   80739400      63.12
2013-05-31  452.50  457.10  449.50  449.73   96075700      62.73
2013-04-30  435.10  445.25  432.07  442.78  172884600      61.35
2013-02-28  444.05  447.87  441.40  441.40   80628800      61.16
2013-01-31  456.98  459.28  454.98  455.49   79833600      62.75
2012-12-31  510.53  535.40  509.00  532.17  164873100      73.31
2012-11-30  586.79  588.40  582.68  585.28   97829900      80.63
2012-10-31  594.88  601.96  587.70  595.32  127500800      81.64
2012-08-31  667.25  668.60  657.25  665.24   84580300      91.23
2012-07-31  603.23  611.70  602.72  610.76  115581900      83.40
2012-05-31  580.74  581.50  571.46  577.73  122918600      78.89
2012-04-30  597.80  598.40  583.00  583.98  126536200      79.74
2012-02-29  541.56  547.61  535.70  542.44  238002800      74.07
2012-01-31  455.59  458.24  453.07  456.48   97920900      62.33
2011-11-30  381.29  382.28  378.30  382.20  101484600      52.19
2011-10-31  402.42  409.33  401.05  404.78   96375300      55.27
2011-09-30  387.12  388.89  381.18  381.32  136910200      52.07
2011-08-31  390.57  392.08  381.86  384.83  130646600      52.55
2011-06-30  334.70  336.13  332.84  335.67   80738700      45.83
2011-05-31  341.10  347.83  341.00  347.83  104438600      47.49
2011-03-31  346.36  349.80  346.06  348.51   68504800      47.59
2011-02-28  351.24  355.05  351.12  353.21  100768500      48.23
...            ...     ...     ...     ...        ...        ...
1984-07-31   25.50   25.87   24.88   25.50   49907200       0.40
1984-05-31   29.00   29.75   28.75   29.37   41753600       0.46
1984-04-30   30.13   31.38   29.87   31.38   73287200       0.49
1984-02-29   25.50   26.87   25.25   26.25   33510400       0.41
1984-01-31   24.75   25.25   23.13   24.75   86273600       0.39
1983-11-30   20.75   21.00   20.38   20.38   16083200       0.32
1983-10-31   21.12   23.00   21.12   22.63   43293600       0.35
1983-09-30   22.75   23.63   22.50   23.13   29467200       0.36
1983-08-31   33.13   37.25   33.13   37.25   50058400       0.58
1983-06-30   49.12   50.00   48.62   48.88   27641600       0.76
1983-05-31   59.25   59.25   56.62   57.75   11384800       0.90
1983-03-31   44.25   44.50   42.25   42.25   21285600       0.66
1983-02-28   46.75   46.87   45.50   45.62   33073600       0.71
1983-01-31   41.00   41.62   40.13   40.87   47000800       0.64
1982-12-31   30.00   30.37   29.87   29.87   12415200       0.47
1982-11-30   28.87   32.00   28.75   31.88   39799200       0.50
1982-09-30   18.37   18.37   18.25   18.25   18670400       0.28
1982-08-31   18.00   18.12   18.00   18.00   35140000       0.28
1982-06-30   12.75   12.87   12.75   12.75   16906400       0.20
1982-04-30   14.75   14.87   14.75   14.75   69350400       0.23
1982-03-31   16.88   17.00   16.88   16.88   12538400       0.26
1981-12-31   22.13   22.25   22.13   22.13   13664000       0.34
1981-11-30   18.75   18.75   18.63   18.63    5992000       0.29
1981-09-30   15.25   15.37   15.25   15.25   12499200       0.24
1981-08-31   20.13   20.25   20.13   20.13   10236800       0.31
1981-07-31   25.00   25.12   25.00   25.00    2738400       0.39
1981-06-30   26.13   26.13   26.00   26.00    8976800       0.41
1981-04-30   28.38   28.62   28.38   28.38    3152800       0.44
1981-03-31   24.75   24.75   24.50   24.50    3998400       0.38
1980-12-31   34.25   34.25   34.13   34.13    8937600       0.53

[283 rows x 6 columns]

### Step 9.  What is the difference in days between the first day and the oldest

In [36]:
number_of_days = (apple.index[0] - apple.index[-1]).days
number_of_days

12291L

In [38]:
first = apple.index[0]
last = apple.index[-1]

### Step 10.  How many months in the data we have?

In [42]:
from datetime import datetime
from dateutil import relativedelta

r = relativedelta.relativedelta(last, first)
r.months

-7

### Step 11. Plot the 'Adj Close' value. Set the size of the figure to 13.5 x 9 inches

### BONUS: Create your own question and answer it.